/**************************************************************************
 *
 *  flt2vrml.c
 *
 *  This file is free software and comes without any warranty.
 *  You can redistribute it and / or modify it under the terms of the
 *  GNU General Public License, version 2, as published by the
 *  Free Software Foundation (see file named COPYING for details).
 *
 *  Copyright (C) 1998-1999 by Systems in Motion.  All rights reserved.
 *
 **************************************************************************/

#include <stdio.h>
#include <assert.h>

#include <profit/util/bfile.h>
#include <profit/model.h>

#include "array.h"
#include "bsptree.h"

#define FLT2VRML_VERSION "0.2"

/**************************************************************************/

void flt2vrml( prf_model_t * model, FILE * file );

int
main(
    int argc,
    char ** argv )
{
    bfile_t * modelfile;
    prf_model_t * model;
    FILE * vrml;

    if ( argc == 1 || argc > 3 ) {
        fprintf( stderr, "Usage: %s <flt-file> [<filename.wrl>]\n", argv[0] );
        return -1;
    }

    prf_init();

    modelfile = bf_create_r( argv[1] );
    if ( ! modelfile ) {
        fprintf( stderr, "Error: Couldn't open file named \"%s\".\n", argv[1] );
        prf_exit();
        return -1;
    }

    model = prf_model_create();
    assert( model != NULL );
    prf_model_poolmem( model );

    if ( ! prf_model_load( model, modelfile ) ) {
        bf_destroy( modelfile );
        prf_model_destroy( model );
        prf_exit();
        fprintf( stderr, "Error: Couldn't load Open Flight file \"%s\".\n",
            argv[1] );
        return -1;
    }
    bf_destroy( modelfile );

    if ( argc == 3 ) {
        vrml = fopen( argv[2], "w" );
        if ( ! vrml ) {
            perror( "fopen()" );
            prf_model_destroy( model );
            prf_exit();
            return -1;
        }
    } else {
        vrml = stdout;
    }

    flt2vrml( model, vrml );

    if ( argc == 3 ) fclose( vrml );
    prf_model_destroy( model );
    prf_exit();
    return 0;
} /* main() */

/**************************************************************************/

void
flt2vrml(
    prf_model_t * model,
    FILE * file )
{
    fprintf( vrml, "#VRML 1.0 ascii\n" );
    fprintf( vrml, "#[generated by flt2vrml v" FLT2VRML_VERSION "]\n" );
    fprintf( vrml, "\n" );

    fprintf( vrml, "\n" );
} /* flt2vrml() */

/**************************************************************************/
