/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Name of package */
#define PACKAGE "profit"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "<coin-support@coin3d.org>"

/* Define to the full name of this package. */
#define PACKAGE_NAME "profit"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "profit 0.9.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "profit"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.9.1"

/* the current profit interface age */
#define PROFIT_INTERFACE_AGE 0

/* the current profit interface revision */
#define PROFIT_INTERFACE_REVISION 0

/* the current profit interface version */
#define PROFIT_INTERFACE_VERSION 0

/* the major part of the profit release version number */
#define PROFIT_MAJOR_VERSION 0

/* the micro part of the profit release version number */
#define PROFIT_MICRO_VERSION 1

/* the minor part of the profit release version number */
#define PROFIT_MINOR_VERSION 9

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.9.1"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */
